PlacesMVCpractice/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PlacesMVCpractice.Models
{
    public class User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string PreferredVacation { get; set; }
    }
}

PlacesMVCpractice/Models/Vacation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PlacesMVCpractice.Models
{
    public class Vacation
    {
        public int Id { get; set; }
        public string PlaceName { get; set; }
        public string Description { get; set; }
        public string ImageName { get; set; }
    }
}

PlacesMVCpractice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlacesMVCpractice.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }


        
    }
}

PlacesMVCpractice/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using PlacesMVCpractice.DAL;
using PlacesMVCpractice;
using PlacesMVCpractice.Models;
using System.Web.Mvc;

namespace PlacesMVCpractice.Controllers
{
    public class UserController : Controller
    {
        private readonly UsersSqlDAL userDal;

       public ActionResult Input()
        {
            return View("Input");
        }

      public ActionResult Index()
        {
            UsersSqlDAL userDal = new UsersSqlDAL();
            List<User> users = userDal.GetAllUsers();
            return View("Index", users);
        }

        public ActionResult NewUser()
        {
            return View("Input", new User());
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult NewUser(User newUser)
        {
            UsersSqlDAL userDal = new UsersSqlDAL();
            var result = userDal.SaveNewUser(newUser);

            return RedirectToAction("Index");
        }

        private ActionResult RedirectToAction(string v)
        {
            throw new NotImplementedException();
        }
    }
}
        

PlacesMVCpractice/Controllers/VacationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PlacesMVCpractice.DAL;
using PlacesMVCpractice.Models;

namespace PlacesMVCpractice.Controllers
{
    public class VacationController : Controller
    {
        private readonly VacationSqlDAL vacationDal;

        // GET: Vacation
        public ActionResult Index()
        {
            VacationSqlDAL vacationDal = new VacationSqlDAL();
            List<Vacation> vacations = vacationDal.GetList();
           
            return View("Index", vacations);
        }

        // GET: Store/Detail/id
        public ActionResult Detail(int id)
        {
          
            VacationSqlDAL vacationDal = new VacationSqlDAL();
            var vacation = vacationDal.GetDetail(id);
            if (vacation == null)
            {
                return new HttpNotFoundResult(); //404
            }

            return View("Detail", vacation);
        }

        //----
        // GET: Vacation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vacation/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vacation/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Vacation/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vacation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Vacation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PlacesMVCpractice/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PlacesMVCpractice/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>This is a text page</h1>

PlacesMVCpractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <h1>Vacation Options</h1>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Carolyn Jillson</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PlacesMVCpractice/Views/User/Index.cshtml
@model IEnumerable<PlacesMVCpractice.Models.User>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You successfully added a User to the database.</h2>

PlacesMVCpractice/Views/User/Input.cshtml
@model PlacesMVCpractice.Models.User
@{
    ViewBag.Title = "Input";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User Input</h2>

@using (Html.BeginForm("Input", "User", FormMethod.Post))
{
    <h4>Users</h4>
    <div class="form-group">
        <div class="form-field">
            @Html.Label("firstName", "FirstName")
            @Html.TextBoxFor(M => M.FirstName)
            </div>
            <div class="form-field">
                @Html.Label("preferredVacation", "PreferredVacation")
                @Html.TextBoxFor(M => M.PreferredVacation)
            </div> 
        <button type="submit">
            @Html.ActionLink("Submit", "Index")
        </button>
    
        </div>
       
}

PlacesMVCpractice/Views/Vacation/Detail.cshtml
@model PlacesMVCpractice.Models.Vacation
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail Page</h2>
<div class="detailDisplay">
    <H1> @Model.PlaceName</H1>
    <div class="product-data">
        
        <H2 class="description">@Model.Description</H2>
    </div>
    <a href="@Url.Action("Detail", "Vacation", new { id = Model.Id })">
        <img id="detailImage"src="@Url.Content("~/Content/" + Model.ImageName)" width="500" align="middle"/>
    </a>

    
</div>

PlacesMVCpractice/Views/Vacation/Index.cshtml
@model List<PlacesMVCpractice.Models.Vacation> 
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Here are several vacation options</h1>
<p></p>
               <div class="vacations">
                   @foreach (var vacation in Model)
                   {
                       <div class="listing">
                          
                           <div class="product-data">
                               <H3 class="title">@vacation.PlaceName</H3> 
                           </div>
                               <a href="@Url.Action("Detail", "Vacation", new { id = vacation.Id })">
                                   <img src="@Url.Content("~/Content/" + vacation.ImageName)" class="image"/>
                               </a>
                           @using (Html.BeginForm("Input", "User", FormMethod.Post))
                           {
                               <div class="form-field">
                                   @Html.RadioButton("vote", @vacation.PlaceName)
                               </div>
                           } 
 
                       </div>
                  
                   }
               </div>
<button type="submit">Submit!</button>

<p>Would you like to add a user to our database?</p>
<form action="@Url.Action("Input", "User")">
    <input type="submit" value="Add user" />
</form>